"""Hubinet Ops 0.5 persistent inventory authority core."""

from .authority import InventoryAuthority
from .canonicalization import (
    CANONICALIZATION_CONTRACT_VERSION,
    canonicalize_transport_locator,
)
from .models import (
    AuthorityConflict,
    AuthorityDatabaseRejected,
    AuthorityError,
    AuthorityInvariantError,
    AuthorityNotFound,
    BackendInstance,
    DiscoveryRun,
    DiscoveryRunLifecycle,
    EndpointLifecycle,
    InventorySource,
    InventorySourceState,
    InventoryNode,
    PersistentSourceFreshness,
    PersistentSourceHealth,
    PersistentSourceHealthOrigin,
    ResourceTermination,
    SourceEndpoint,
    SourceRuntimeHealth,
    ResourceIncarnation,
    ResourceLocatorBinding,
)
from .discovery import (
    BaselineCompleteness,
    BaselineMode,
    DetailReadStatus,
    DiscoveryRunCompletionEvidence,
    DiscoveredNode,
    DiscoveredResource,
    NormalizedDiscoverySnapshot,
    SourceAvailability,
)
from .provider import (
    BoundaryBaselineResult,
    ENDPOINT_ACL_MATRIX,
    PROVIDER_CONTRACT_VERSION,
    ProviderContractError,
    ProviderFailureKind,
    ProxmoxProviderV1,
    ReadOnlyProviderTransport,
    classify_boundary,
    classify_provider_failure,
    evaluate_permission_coverage,
    validate_supported_pve_release,
)
from .publication import InventoryPublication, PublishedInventoryView
from .reconciliation import ReconciliationSummary
from .store import InventoryAuthorityStore

__all__ = [
    "AuthorityConflict",
    "AuthorityDatabaseRejected",
    "AuthorityError",
    "AuthorityInvariantError",
    "AuthorityNotFound",
    "BackendInstance",
    "BaselineCompleteness",
    "BaselineMode",
    "BoundaryBaselineResult",
    "CANONICALIZATION_CONTRACT_VERSION",
    "DiscoveryRun",
    "DiscoveryRunCompletionEvidence",
    "DiscoveryRunLifecycle",
    "DetailReadStatus",
    "DiscoveredNode",
    "DiscoveredResource",
    "ENDPOINT_ACL_MATRIX",
    "EndpointLifecycle",
    "InventoryAuthority",
    "InventoryAuthorityStore",
    "InventorySource",
    "InventorySourceState",
    "InventoryNode",
    "InventoryPublication",
    "NormalizedDiscoverySnapshot",
    "PersistentSourceFreshness",
    "PersistentSourceHealth",
    "PersistentSourceHealthOrigin",
    "PROVIDER_CONTRACT_VERSION",
    "ProviderContractError",
    "ProviderFailureKind",
    "ProxmoxProviderV1",
    "PublishedInventoryView",
    "ReadOnlyProviderTransport",
    "ReconciliationSummary",
    "ResourceIncarnation",
    "ResourceLocatorBinding",
    "ResourceTermination",
    "SourceAvailability",
    "SourceEndpoint",
    "SourceRuntimeHealth",
    "canonicalize_transport_locator",
    "classify_boundary",
    "classify_provider_failure",
    "evaluate_permission_coverage",
    "validate_supported_pve_release",
]
