#!/usr/bin/env bash
# Phase 6 -- dedicated read-only PVE identity (user/role/token).
# Phase 7 -- PVE TLS trust material.
#
# Exact shape mirrors docs/operations/0.5-r0-operational-activation.md
# section 2, automated: user hubinetops@pve, role HubinetOpsR0Auditor with
# privileges exactly Sys.Audit,VM.Audit, token r0-readonly with privsep=1,
# ACL granted to BOTH the user and the token at path / with propagate 1.
#
# Fresh-install semantics only (see docs/README section "Idempotency"):
# any pre-existing user/role/token with these exact names is a conflict
# and STOPs the run -- this bootstrap never silently adopts an existing
# identity of unknown provenance.
#
# Secret handling: the raw token secret never enters this script's own
# argv or a bash variable except as bytes redirected directly between two
# files/processes (see PVE_TOKEN_SECRET_FILE below and bootstrap-common.sh
# _json_string_value). It is never passed to jq/python3/awk as a literal
# -a/-v/positional argument.
#
# Ownership/rollback race (TOCTOU): the pre-existing-conflict checks above
# only close the window BEFORE this phase starts, not a race between two
# concurrent bootstrap runs (same or different PVE cluster node) that both
# observe the fixed-name user/role/token as absent and then both attempt
# to create it. PVE itself resolves that race (only one `pveum user add`
# can win), but the LOSING run's own call then fails -- and a naive
# rollback that unconditionally deletes "the object matching our fixed
# name" would delete the WINNING run's legitimately-created object. This
# is a cluster-wide identity namespace; a local-node lock cannot prove
# ownership against another node. The fix: BOOTSTRAP_RUN_ID (a random
# per-invocation identifier, generated by the entrypoint) is embedded in
# every PVE object comment this bootstrap creates that supports one (user,
# token). Rollback (bootstrap-proxmox-0.5.sh::rollback_on_failure) never
# deletes an object merely because it exists and matches our fixed name --
# it deletes only what this run can PROVE, via a live read-back performed
# immediately before deletion, still carries this exact run-id in its
# comment field RIGHT NOW.
#
# Third-pass corrective note: an earlier version of
# _user_object_owned_by_this_run / _token_object_owned_by_this_run treated
# `ledger_has` (this run's OWN record that its create call once succeeded)
# as sufficient proof by itself, returning immediately without any live
# re-query. That proves only "this run created an object with this name
# AT SOME EARLIER POINT," not "the CURRENT object is still that same
# object" -- if the object was deleted and replaced by another actor
# between this run's own successful creation and a later phase failing
# and triggering rollback, the ledger-only fast path would still report
# "owned" and delete the replacement. Both functions now ALWAYS perform a
# live read-back of the CURRENT object's comment and require it to carry
# `run=${BOOTSTRAP_RUN_ID}` before returning true; `ledger_has` is
# consulted only as diagnostic context (to log a specific "replaced since
# creation" warning), never as an independent deletion authorization. A
# read-back command failure, malformed JSON, a missing object, or a
# comment that does not match are all treated identically: NOT owned,
# preserve, log actionable remediation.
#
# PVE roles have no comment/description field at all, so this same live-
# provenance check is structurally impossible for them -- a role's
# ownership can never be re-verified at delete-time, only inferred from
# this run's own ledger, which (per the reasoning above) is not
# sufficient proof that the CURRENT role is still this run's role. The
# conservative policy adopted here: PVE-identity rollback NEVER deletes
# HubinetOpsR0Auditor automatically, regardless of ledger state. A failed
# run that got as far as creating the role always leaves it in place, with
# a loud manual-remediation message; a retried bootstrap will then hit the
# pre-existing-conflict check in this phase and fail closed until an
# operator has inspected and removed it. This is a deliberate
# completeness/safety tradeoff: an automatic rollback that could delete
# someone else's role is a worse outcome than an orphaned role from a
# failed run that requires one manual `pveum role delete` before retrying.
#
# Residual, structurally unavoidable race: even with the live read-back
# above, there is no PVE-exposed atomic "verify-then-delete"
# (compare-and-delete) primitive for users or tokens -- an external actor
# could, in principle, replace the object in the narrow window between
# this run's read-back check and its subsequent `pveum ... delete` call.
# This bootstrap does not attempt to close that residual window with
# retries or additional locking (PVE gives no cluster-wide primitive that
# would make a retry any safer, only more complex); it is documented here
# accurately as an accepted, external-administrator-only residual risk,
# not claimed as fully solved.

PVE_USER="hubinetops@pve"
PVE_ROLE="HubinetOpsR0Auditor"
PVE_TOKEN_ID="r0-readonly"
PVE_FULL_TOKEN_ID="${PVE_USER}!${PVE_TOKEN_ID}"
# The exact, complete set this bootstrap ever grants -- not a minimum, not
# a blacklist of what to avoid: verification (see _verify_effective_permissions
# below) asserts the token's effective privilege set equals this set
# exactly, so any unexpected additional privilege (however named) is
# caught, not just the specific mutation privileges named in comments
# elsewhere in this repo's docs.
PVE_REQUIRED_PRIVS="Sys.Audit,VM.Audit"

phase6_pve_identity() {
  log_phase "Phase 6: dedicated read-only PVE identity"

  _assert_pve_object_absent "userid" "${PVE_USER}" "PVE user '${PVE_USER}'" \
    "pveum user delete ${PVE_USER}" pveum user list --output-format json
  _assert_pve_object_absent "roleid" "${PVE_ROLE}" "PVE role '${PVE_ROLE}'" \
    "pveum role delete ${PVE_ROLE}" pveum role list --output-format json

  # Recorded only NOW -- after both pre-existing-conflict checks above,
  # immediately before the first real mutation -- never before them. If
  # this marker were recorded earlier, a conflict-refusal die() (which
  # touches nothing) would still make rollback attempt to delete a
  # PRE-EXISTING user/role/token this run never created, violating "never
  # touch a pre-existing resource." From this point on, if a later step
  # mutates PVE state but then reports a nonzero exit for an unrelated
  # reason (a real possibility with `pveum`, not merely local bash control
  # flow), rollback still knows to attempt cleanup of every object this
  # phase might have touched -- see rollback_on_failure in
  # bootstrap-proxmox-0.5.sh, which gates the whole PVE-identity cleanup
  # block on this single marker rather than on each sub-step's own
  # success-only ledger entry.
  ledger_record pve-identity-attempted "${PVE_USER}"

  run_logged pveum user add "${PVE_USER}" --comment "Hubinet Ops 0.5 R0 read-only discovery (created by bootstrap-proxmox-0.5.sh; run=${BOOTSTRAP_RUN_ID})" \
    || die "failed to create PVE user ${PVE_USER}"
  ledger_record pve-user "${PVE_USER}"

  run_logged pveum role add "${PVE_ROLE}" --privs "${PVE_REQUIRED_PRIVS}" \
    || die "failed to create PVE role ${PVE_ROLE}"
  ledger_record pve-role "${PVE_ROLE}"

  run_logged pveum acl modify / --users "${PVE_USER}" --roles "${PVE_ROLE}" --propagate 1 \
    || die "failed to grant role ${PVE_ROLE} to user ${PVE_USER} at /"
  ledger_record pve-acl-user "${PVE_USER}"

  # This output contains the raw token secret in its "value" field -- use
  # secret_tmpfile (restrictive mode, tracked for guaranteed cleanup on
  # ANY exit path, including a die() below) rather than an ad hoc path,
  # so a parse failure can never leave the secret behind unregistered.
  local token_create_output
  token_create_output="$(secret_tmpfile "/tmp/hubinet-ops-bootstrap-token-create.XXXXXX.json")"
  run_logged pveum user token add "${PVE_USER}" "${PVE_TOKEN_ID}" --privsep 1 \
    --comment "R0 read-only discovery token (created by bootstrap-proxmox-0.5.sh; run=${BOOTSTRAP_RUN_ID})" \
    --output-format json >"${token_create_output}" \
    || die "failed to create token ${PVE_FULL_TOKEN_ID}"
  ledger_record pve-token "${PVE_FULL_TOKEN_ID}"

  # The secret bytes move directly from the parser's stdout to this file
  # via redirection -- they are never assigned to a bash variable, never
  # passed as an argv element, and never touch this script's own
  # environment.
  PVE_TOKEN_SECRET_FILE="$(secret_tmpfile "/tmp/hubinet-ops-bootstrap-token.XXXXXX")"
  _json_string_value "${token_create_output}" "value" >"${PVE_TOKEN_SECRET_FILE}" \
    || die "could not parse the PVE token secret from 'pveum user token add' output"
  [[ -s "${PVE_TOKEN_SECRET_FILE}" ]] || die "PVE token secret was empty after creation -- refusing to continue"

  # privsep=1 means the token has NO effective permissions of its own
  # until it receives its own ACL grant (runbook section 2.4 step 4) --
  # skipping this step produces an authenticated-but-zero-privilege token.
  run_logged pveum acl modify / --tokens "${PVE_FULL_TOKEN_ID}" --roles "${PVE_ROLE}" --propagate 1 \
    || die "failed to grant role ${PVE_ROLE} to token ${PVE_FULL_TOKEN_ID} at /"
  ledger_record pve-acl-token "${PVE_FULL_TOKEN_ID}"

  _verify_effective_permissions

  log_pass "PVE identity: ${PVE_USER}, role ${PVE_ROLE} (exactly ${PVE_REQUIRED_PRIVS}), token ${PVE_TOKEN_ID} (privsep=1)"
}

# _assert_pve_object_absent <id-field> <id-value> <label> <delete-hint> <list-cmd...>
# Fail-closed pre-existing-conflict check. Third-pass corrective note: an
# earlier version ran the listing command with `... || true` and then
# checked _json_list_field_equals on whatever (possibly empty/garbage)
# file resulted -- a transient `pveum` error, a rejected --output-format
# flag, an unreachable pmxcfs, or truncated output would then be
# indistinguishable from "the object genuinely does not exist," and the
# run would proceed to create a PVE identity anyway. This helper
# distinguishes four outcomes and only ever proceeds on the fourth:
#   - the listing command itself fails                       -> STOP
#   - it succeeds but the output is not valid JSON             -> STOP
#   - a valid JSON array is read and the target id IS present  -> STOP
#     (a real pre-existing-object conflict)
#   - a valid JSON array is read and the target id is absent   -> proceed
_assert_pve_object_absent() {
  local id_field="$1" id_value="$2" label="$3" delete_hint="$4"
  shift 4
  local -a list_cmd=("$@")

  local list_file
  list_file="$(mktemp /tmp/hubinet-ops-bootstrap-conflictcheck.XXXXXX.json)" \
    || die "could not create a temp file to inspect pre-existing PVE identity state for ${label}"
  chmod 0600 "${list_file}"

  local cmd_status
  "${list_cmd[@]}" >"${list_file}" 2>/dev/null && cmd_status=0 || cmd_status=$?
  if (( cmd_status != 0 )); then
    rm -f "${list_file}"
    die "could not verify whether ${label} already exists ('${list_cmd[*]}' failed with exit ${cmd_status}) -- refusing to proceed without a reliable read of existing PVE identity state. This is a fail-closed pre-existing-conflict check, not a transient warning; retry once the PVE API is reliably reachable."
  fi

  if ! _json_list_is_valid "${list_file}"; then
    rm -f "${list_file}"
    die "could not verify whether ${label} already exists ('${list_cmd[*]}' did not produce a valid JSON array) -- refusing to proceed without a reliable read of existing PVE identity state."
  fi

  if _json_list_field_equals "${list_file}" "${id_field}" "${id_value}"; then
    rm -f "${list_file}"
    die "${label} already exists -- this bootstrap only performs a fresh install and will not reuse an existing identity of unknown provenance. Remove it yourself (${delete_hint}) after confirming it is not depended on elsewhere, then retry."
  fi
  rm -f "${list_file}"
}

# _verify_effective_permissions: exact-set proof, not a blacklist. Reads
# back the token's own effective permissions and asserts the sorted set of
# truthy privilege keys equals PVE_REQUIRED_PRIVS exactly -- catches ANY
# unexpected privilege (a missing required one, or any extra one, whatever
# its name) rather than only the specific mutation-shaped privilege names
# a fixed pattern happens to enumerate.
_verify_effective_permissions() {
  local perms_file
  perms_file="$(mktemp /tmp/hubinet-ops-bootstrap-perms.XXXXXX.json)"
  chmod 0600 "${perms_file}"
  if ! pveum user token permissions "${PVE_USER}" "${PVE_TOKEN_ID}" --path / --output-format json >"${perms_file}" 2>/dev/null; then
    rm -f "${perms_file}"
    die "could not read back effective permissions for ${PVE_FULL_TOKEN_ID}"
  fi

  # `... && parse_status=0 || parse_status=$?` rather than a plain
  # assignment: under `set -e`, a bare `actual_keys="$(cmd)"` where cmd
  # exits nonzero makes the assignment itself "fail," triggering errexit
  # and aborting the script right here -- before parse_status could ever
  # be inspected or the die() message below could run.
  local actual_keys parse_status
  actual_keys="$(_json_truthy_keys_sorted "${perms_file}")" && parse_status=0 || parse_status=$?
  rm -f "${perms_file}"
  (( parse_status == 0 )) \
    || die "could not parse effective-permission JSON for ${PVE_FULL_TOKEN_ID} (requires jq or python3 on the PVE host -- checked in phase1)"

  local expected_keys
  expected_keys="$(printf '%s\n' "${PVE_REQUIRED_PRIVS//,/$'\n'}" | LC_ALL=C sort)"

  if [[ "${actual_keys}" != "${expected_keys}" ]]; then
    local actual_csv
    actual_csv="$(printf '%s' "${actual_keys}" | tr '\n' ',' | sed 's/,$//')"
    die "verification failed: token ${PVE_FULL_TOKEN_ID} effective privileges are exactly {${actual_csv:-<none>}} but must be exactly {${PVE_REQUIRED_PRIVS}} -- refusing to continue with a credential whose privilege set is not provably read-only (this is an exact-set check: any missing required privilege OR any unexpected extra privilege fails it)"
  fi
}

# ---------------------------------------------------------------------------
# Ownership-proof functions -- used only by rollback (bootstrap-proxmox-
# 0.5.sh::rollback_on_failure), never by the forward-creation path above,
# which already stops immediately (`|| die`) on any failure. These answer
# exactly one question for each PVE object type this phase can create:
# "can THIS run prove it created this object?" -- never "does an object
# matching our fixed name currently exist?" A concurrent bootstrap run (or
# any other creator) racing for the same fixed name is a real possibility
# in a cluster-wide identity namespace; rollback must never delete an
# object it cannot prove it owns.
# ---------------------------------------------------------------------------

# _user_object_owned_by_this_run: true only if a LIVE read-back, performed
# right now, shows the CURRENT user object's comment field carries this
# exact run's BOOTSTRAP_RUN_ID -- which only this run's own `pveum user
# add` call could have written. `ledger_has` (this run's own record that
# its create call once succeeded) is consulted only to produce a more
# specific diagnostic message when the live check disagrees with it; it
# never authorizes deletion by itself. A read-back command failure,
# invalid JSON, a missing object, or a non-matching/absent comment are all
# treated identically: not owned.
_user_object_owned_by_this_run() {
  local had_ledger_record=0
  ledger_has pve-user "${PVE_USER}" && had_ledger_record=1

  local list_file
  list_file="$(mktemp /tmp/hubinet-ops-bootstrap-userlist-rb.XXXXXX.json)" || return 1
  chmod 0600 "${list_file}"
  local cmd_status
  pveum user list --output-format json >"${list_file}" 2>/dev/null && cmd_status=0 || cmd_status=$?
  if (( cmd_status != 0 )); then
    rm -f "${list_file}"
    log_warn "could not read back the current PVE user list to verify ownership of '${PVE_USER}' (pveum exited ${cmd_status}) -- treating ownership as unproven regardless of this run's own ledger history"
    return 1
  fi
  if ! _json_list_is_valid "${list_file}"; then
    rm -f "${list_file}"
    log_warn "could not verify ownership of '${PVE_USER}': the PVE user list did not parse as a valid JSON array -- treating ownership as unproven regardless of this run's own ledger history"
    return 1
  fi

  local comment
  comment="$(_json_list_field_value "${list_file}" "userid" "${PVE_USER}" "comment")"
  rm -f "${list_file}"

  if [[ -z "${comment}" ]]; then
    (( had_ledger_record )) && log_warn "this run's ledger recorded creating '${PVE_USER}', but it no longer exists at rollback time -- nothing to clean up"
    return 1
  fi
  if [[ "${comment}" == *"run=${BOOTSTRAP_RUN_ID}"* ]]; then
    return 0
  fi
  if (( had_ledger_record )); then
    log_warn "this run's ledger recorded creating '${PVE_USER}', but the CURRENT object's comment does not carry this run's id (run=${BOOTSTRAP_RUN_ID}) -- it appears to have been replaced by another actor since creation; preserving it rather than deleting an object this run can no longer prove is its own"
  fi
  return 1
}

# _token_object_owned_by_this_run: same live-read-back reasoning as the
# user check above, via `pveum user token list <user> --output-format
# json`'s own `comment` field for the matching `tokenid`. Only
# reachable/meaningful once the owning user itself is proven ours (see
# rollback_on_failure) -- a token can only ever exist under a user this
# bootstrap itself just created.
_token_object_owned_by_this_run() {
  local had_ledger_record=0
  ledger_has pve-token "${PVE_FULL_TOKEN_ID}" && had_ledger_record=1

  local list_file
  list_file="$(mktemp /tmp/hubinet-ops-bootstrap-tokenlist-rb.XXXXXX.json)" || return 1
  chmod 0600 "${list_file}"
  local cmd_status
  pveum user token list "${PVE_USER}" --output-format json >"${list_file}" 2>/dev/null && cmd_status=0 || cmd_status=$?
  if (( cmd_status != 0 )); then
    rm -f "${list_file}"
    log_warn "could not read back the current PVE token list for '${PVE_USER}' to verify ownership of '${PVE_TOKEN_ID}' (pveum exited ${cmd_status}) -- treating ownership as unproven regardless of this run's own ledger history"
    return 1
  fi
  if ! _json_list_is_valid "${list_file}"; then
    rm -f "${list_file}"
    log_warn "could not verify ownership of token '${PVE_TOKEN_ID}': the PVE token list did not parse as a valid JSON array -- treating ownership as unproven regardless of this run's own ledger history"
    return 1
  fi

  local comment
  comment="$(_json_list_field_value "${list_file}" "tokenid" "${PVE_TOKEN_ID}" "comment")"
  rm -f "${list_file}"

  if [[ -z "${comment}" ]]; then
    (( had_ledger_record )) && log_warn "this run's ledger recorded creating token '${PVE_FULL_TOKEN_ID}', but it no longer exists at rollback time -- nothing to clean up"
    return 1
  fi
  if [[ "${comment}" == *"run=${BOOTSTRAP_RUN_ID}"* ]]; then
    return 0
  fi
  if (( had_ledger_record )); then
    log_warn "this run's ledger recorded creating token '${PVE_FULL_TOKEN_ID}', but the CURRENT object's comment does not carry this run's id (run=${BOOTSTRAP_RUN_ID}) -- it appears to have been replaced by another actor since creation; preserving it rather than deleting an object this run can no longer prove is its own"
  fi
  return 1
}

# _role_object_owned_by_this_run: PVE roles carry no comment/description
# field this bootstrap could use as a provenance marker, so -- unlike user
# and token above -- there is no PVE-supported mechanism to re-verify at
# rollback time that the CURRENT role is still the one this run created.
# This run's own ledger record proves only "this run's own `pveum role
# add` call succeeded at some earlier point," never "the role currently
# named HubinetOpsR0Auditor is still that same object" (it could have been
# deleted and recreated by another actor in the meantime, exactly as with
# user/token). Since that stronger proof is structurally unavailable for
# roles, the deliberate, conservative policy is to NEVER delete the role
# automatically during rollback, regardless of ledger state -- always
# return false (not owned) here. An orphaned role from a failed run is
# left for the operator to inspect and remove by hand; the next bootstrap
# attempt will then correctly fail closed at phase6's pre-existing-
# conflict check until that happens, rather than risk deleting an object
# that might belong to someone else.
_role_object_owned_by_this_run() {
  return 1
}

# ---------------------------------------------------------------------------
# Phase 7 -- PVE TLS trust material.
#
# TLS_TRUST_MODE default is "" (unset): falling back to the CT's system
# trust store is only ever taken when the operator explicitly opts in with
# --tls-trust system. Auto-detecting the PVE cluster's own CA (or an
# explicit --pve-ca-path) remains the default, safe path and needs no
# opt-in. R0 never supports disabling TLS verification (verify=false).
# ---------------------------------------------------------------------------

phase7_tls_trust() {
  log_phase "Phase 7: PVE TLS trust"

  if [[ "${TLS_TRUST_MODE}" == "system" ]]; then
    # --pve-ca-path + --tls-trust system is already rejected in phase1
    # preflight as mutually exclusive.
    log_info "operator explicitly requested the CT's system trust store (--tls-trust system) -- skipping PVE CA auto-detection/deployment"
    CT_CA_BUNDLE_PATH=""
    log_pass "TLS trust: system trust store (explicit operator opt-in)"
    return 0
  fi

  local ca_source=""
  if [[ -n "${PVE_CA_PATH}" ]]; then
    [[ -f "${PVE_CA_PATH}" ]] || die "--pve-ca-path '${PVE_CA_PATH}' does not exist"
    ca_source="${PVE_CA_PATH}"
  else
    ca_source="$(_detect_pve_ca_bundle)" || true
  fi

  if [[ -z "${ca_source}" ]]; then
    die "could not determine PVE CA trust material and no --pve-ca-path was given. R0 never supports disabling TLS verification. Either pass --pve-ca-path <path-to-pve-root-ca.pem>, or explicitly pass --tls-trust system to opt in to relying on the target CT's system trust store (only correct if the PVE endpoint's certificate chains to a publicly-trusted CA or one you have already installed into the CT's OS trust store yourself) -- this bootstrap never falls back to system trust implicitly."
  fi

  CT_CA_BUNDLE_PATH="/etc/hubinet-ops/pve-ca.pem"
  BOOTSTRAP_CA_SOURCE_PATH="${ca_source}"
  log_pass "TLS trust: explicit CA bundle from ${ca_source} (deployed into the CT at ${CT_CA_BUNDLE_PATH})"
}

# _detect_pve_ca_bundle: the cluster's own CA certificate lives at a fixed,
# well-known path on every PVE host (used internally for pveproxy's own
# certificate chain). This is the standard, safe default source to hand to
# a new CT rather than teaching operators to hunt for it.
_detect_pve_ca_bundle() {
  local candidate="/etc/pve/pve-root-ca.pem"
  [[ -f "${candidate}" ]] && { printf '%s' "${candidate}"; return 0; }
  return 1
}
