#!/usr/bin/env bash
# Phase 8 -- deterministic source transfer + deploy/install-0.5.0-fresh.sh
#            invocation inside the new CT.
# Phase 9 -- source-centric R0 config generation (inventory.yaml, agent.env).

CT_SRC_TARBALL_HOST=""
CT_SRC_TARBALL_CT="/tmp/hubinet-ops-src.tar.gz"
CT_SRC_DIR_CT="/tmp/hubinet-ops-src"

phase8_deploy_source() {
  log_phase "Phase 8: deploy Hubinet Ops source into the container"

  CT_SRC_TARBALL_HOST="$(secret_tmpfile "/tmp/hubinet-ops-bootstrap-src.XXXXXX.tar.gz")"
  # Not actually secret content, but reusing secret_tmpfile gets us a
  # restrictive 0600 temp file and guaranteed cleanup on exit for free.

  if git -C "${SOURCE_DIR}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    # Exactly the tracked release payload -- .git, gitignored venvs/caches/
    # logs/runtime DBs, and any local untracked developer files are never
    # included, because they were never tracked in the first place
    # (scripts/check_tracked_files.py enforces this repository-wide).
    run_logged_redacted "git -C ${SOURCE_DIR} archive HEAD -o <tarball>" \
      git -C "${SOURCE_DIR}" archive HEAD -o "${CT_SRC_TARBALL_HOST}" \
      || die "git archive of ${SOURCE_DIR} failed"
  else
    log_warn "SOURCE_DIR is not a git checkout -- falling back to a filtered tar (this path is less strongly guaranteed than 'git archive'; prefer running the bootstrap from a real git checkout)"
    run_logged_redacted "tar -czf <tarball> --exclude=... ${SOURCE_DIR}" \
      tar -czf "${CT_SRC_TARBALL_HOST}" \
        --exclude=".git" \
        --exclude=".venv" \
        --exclude="venv" \
        --exclude="__pycache__" \
        --exclude="*.pyc" \
        --exclude=".pytest_cache" \
        --exclude="*.db" --exclude="*.db-wal" --exclude="*.db-shm" \
        --exclude="*.log" \
        --exclude=".env" \
        -C "${SOURCE_DIR}" . \
      || die "tar of ${SOURCE_DIR} failed"
  fi

  run_logged pct push "${VMID}" "${CT_SRC_TARBALL_HOST}" "${CT_SRC_TARBALL_CT}" \
    || die "pct push of source tarball into container ${VMID} failed"

  run_logged pct exec "${VMID}" -- mkdir -p "${CT_SRC_DIR_CT}" \
    || die "failed to create ${CT_SRC_DIR_CT} inside container ${VMID}"
  run_logged pct exec "${VMID}" -- tar -xzf "${CT_SRC_TARBALL_CT}" -C "${CT_SRC_DIR_CT}" \
    || die "failed to extract source tarball inside container ${VMID}"
  run_logged pct exec "${VMID}" -- rm -f "${CT_SRC_TARBALL_CT}" \
    || log_warn "could not remove ${CT_SRC_TARBALL_CT} inside the container (non-fatal)"

  log_info "invoking deploy/install-0.5.0-fresh.sh inside container ${VMID}"
  run_logged pct exec "${VMID}" -- bash "${CT_SRC_DIR_CT}/deploy/install-0.5.0-fresh.sh" \
    || die "deploy/install-0.5.0-fresh.sh failed inside container ${VMID} -- see output above; the installer's own fresh-host checks were not weakened by this bootstrap"

  log_pass "source deployed and installer completed inside container ${VMID}"
}

phase9_generate_config() {
  log_phase "Phase 9: generate source-centric R0 configuration"

  local tls_block
  if [[ -n "${CT_CA_BUNDLE_PATH}" ]]; then
    if [[ -n "${BOOTSTRAP_CA_SOURCE_PATH:-}" ]]; then
      run_logged pct push "${VMID}" "${BOOTSTRAP_CA_SOURCE_PATH}" "${CT_CA_BUNDLE_PATH}" \
        || die "failed to push PVE CA bundle into container ${VMID}"
      run_logged pct exec "${VMID}" -- chown root:hubinetops "${CT_CA_BUNDLE_PATH}" \
        || die "failed to chown PVE CA bundle inside container ${VMID}"
      run_logged pct exec "${VMID}" -- chmod 0640 "${CT_CA_BUNDLE_PATH}" \
        || die "failed to chmod PVE CA bundle inside container ${VMID}"
    fi
    tls_block=$'  tls:\n    verify: true\n    ca_bundle_path: "'"${CT_CA_BUNDLE_PATH}"'"'
  else
    tls_block=$'  tls:\n    verify: true\n    ca_bundle_path: null'
  fi

  local inventory_tmp
  inventory_tmp="$(secret_tmpfile "/tmp/hubinet-ops-bootstrap-inventory.XXXXXX.yaml")"
  cat >"${inventory_tmp}" <<YAML
# Generated by deploy/bootstrap-proxmox-0.5.sh -- source-centric only.
# No VMID/LXC/QEMU list exists here or anywhere else in this file; every
# node/resource is discovered dynamically after this bootstrap completes.
source:
  display_name: "${HA_DISPLAY_NAME}"
  provider_kind: proxmox_ve
  pve_endpoint: "${PVE_ENDPOINT}"
  freshness_duration_seconds: ${FRESHNESS_SECONDS}
  credential_reference: "secret://${PVE_TOKEN_ID}-v1"
  pve_token_env: HUBINET_OPS_R0_PVE_TOKEN
${tls_block}

runtime:
  authority_db_path: /var/lib/hubinet-ops/authority.db
  api_token_env: HUBINET_OPS_R0_API_TOKEN
YAML

  run_logged pct push "${VMID}" "${inventory_tmp}" /etc/hubinet-ops/inventory.yaml \
    || die "failed to push generated inventory.yaml into container ${VMID}"
  run_logged pct exec "${VMID}" -- chown root:hubinetops /etc/hubinet-ops/inventory.yaml \
    || die "failed to chown inventory.yaml inside container ${VMID}"
  run_logged pct exec "${VMID}" -- chmod 0640 /etc/hubinet-ops/inventory.yaml \
    || die "failed to chmod inventory.yaml inside container ${VMID}"

  # agent.env: install-0.5.0-fresh.sh already generated a fresh
  # HUBINET_OPS_R0_API_TOKEN inside the container (§ its own step 2). We
  # only need to fill in HUBINET_OPS_R0_PVE_TOKEN -- read the existing
  # file back, replace exactly that one line, never regenerate the API
  # bearer token the installer already created.
  local existing_env_tmp
  existing_env_tmp="$(secret_tmpfile "/tmp/hubinet-ops-bootstrap-agentenv-read.XXXXXX")"
  run_logged pct exec "${VMID}" -- cat /etc/hubinet-ops/agent.env >"${existing_env_tmp}" \
    || die "failed to read /etc/hubinet-ops/agent.env from container ${VMID} (was it created by install-0.5.0-fresh.sh?)"

  local pve_token
  pve_token="$(cat "${PVE_TOKEN_SECRET_FILE}")"
  local new_env_tmp
  new_env_tmp="$(secret_tmpfile "/tmp/hubinet-ops-bootstrap-agentenv-write.XXXXXX")"
  awk -v token="${pve_token}" -v full_token_id="${PVE_FULL_TOKEN_ID}" '
    /^HUBINET_OPS_R0_PVE_TOKEN=/ { print "HUBINET_OPS_R0_PVE_TOKEN=" full_token_id "=" token; next }
    { print }
  ' "${existing_env_tmp}" >"${new_env_tmp}"

  run_logged_redacted "pct push <container> <redacted agent.env> /etc/hubinet-ops/agent.env" \
    pct push "${VMID}" "${new_env_tmp}" /etc/hubinet-ops/agent.env \
    || die "failed to push updated agent.env into container ${VMID}"
  run_logged pct exec "${VMID}" -- chown root:hubinetops /etc/hubinet-ops/agent.env \
    || die "failed to chown agent.env inside container ${VMID}"
  run_logged pct exec "${VMID}" -- chmod 0640 /etc/hubinet-ops/agent.env \
    || die "failed to chmod agent.env inside container ${VMID}"

  # Capture the R0 API bearer token (needed for phase 12 acceptance and the
  # final summary's "next steps", but never printed) directly from the file
  # we just wrote -- avoids a second round-trip into the container.
  R0_API_BEARER_TOKEN="$(grep '^HUBINET_OPS_R0_API_TOKEN=' "${new_env_tmp}" | cut -d= -f2-)"
  [[ -n "${R0_API_BEARER_TOKEN}" ]] || die "could not determine the R0 API bearer token after config generation"

  log_pass "generated source-centric inventory.yaml and agent.env (0640, root:hubinetops)"
}
